apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
        - name: workflow-controller
          image: gcr.lank8s.cn/ml-pipeline/workflow-controller:v3.3.8-license-compliance
          args:
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            - gcr.lank8s.cn/ml-pipeline/argoexec:v3.3.8-license-compliance
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
